name: m4-serial-forward-python

services:

  m4-serial-forward-python:
    image: hub.foundries.io/${FACTORY}/m4-serial-forward-python:latest
    restart: unless-stopped
    environment:
    - PYTHONUNBUFFERED=1  
    read_only: true
    ports:
    - "5002-5020:5002-5020"
    volumes:
    - "/tmp:/tmp"
    devices:
    - "/dev/ttyGS0"
    extra_hosts:
    - "m4-proxy:host-gateway"
