name: m4-serial-forward-go

services:

  m4-serial-forward-go:
    image: hub.foundries.io/${FACTORY}/m4-serial-forward-go:latest
    restart: unless-stopped
    read_only: true
    user: "0"
    volumes:
    - "/tmp:/tmp"
    devices:
    - "/dev/ttyGS0"
    ports:
    - "5002:5002"
    extra_hosts:
    - "m4-proxy:172.17.0.1"
